### ISSUE TITLE
用HDR生成环境数据时，存在空白间隙问题

### ISSUE THREAD

**Issue by tienya** [dtysky/xr-frame-toolkit#4]
通过标准HDR格式的图片生成环境数据时，缝合处存在较明显的空白间隙

<img width="864" alt="image" src="https://github.com/dtysky/xr-frame-toolkit/assets/16622106/21046595-4394-4ddb-8b51-25041288e69a">

使用的是 MacOS 版本，

HDR图片

https://github.com/google/model-viewer/raw/master/packages/shared-assets/environments/neutral.hdr

**Comment by dtysky** [comment]
同样的连接下载最新的版本试试。
